INFO - 2023-09-29 13:18:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:18:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:18:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:18:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:23:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:23:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:23:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:48:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:48:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:48:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:48:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:48:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:50:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:50:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:52:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:52:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:52:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 13:52:09 --> mysqli_sql_exception: Unknown column 'nome' in 'field list' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `st...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `st...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `st...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `st...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(46): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(45): App\Modules\Admin\Models\UserModel->newRecord(Array)
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('new')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 13:52:09 --> Unknown column 'nome' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `st_table_record` (`nome`, `sobrenome`, `cpf`, `dt_contratacao`, `ativo`, `departamento`) VALUES (:nome:, :sobrenome:, :cpf:, :dt_contratacao:, :ativo:, :departamento:)', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(46): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Modules\Admin\Controllers\Users.php(45): App\Modules\Admin\Models\UserModel->newRecord([...])
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('new')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 13:52:10 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'nome' in 'field list'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `st...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(46): CodeIgniter\Database\BaseBuilder->insert(Array)
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(45): App\Modules\Admin\Models\UserModel->newRecord(Array)
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('new')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 13:53:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:53:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:54:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:54:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:55:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 13:59:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:00:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:00:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:00:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:01:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:02:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:02:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:02:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:03:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:05:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:10:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:10:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:10:35 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:10:35 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:10:35 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:11:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:11:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:11:24 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:11:24 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:11:24 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:11:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:11:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:11:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:11:33 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:11:33 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:11:33 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:13:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:13:15 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:13:15 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:13:15 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:13:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:13:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:13:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:14:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:14:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:14:22 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:14:22 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:14:22 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:14:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:16:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:16:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:16:09 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:16:09 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:16:09 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:17:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:17:19 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:17:19 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:17:19 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:17:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:17:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:17:22 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:17:22 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:17:22 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:22:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:22:32 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:22:32 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:22:32 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:22:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:22:33 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:22:33 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:22:33 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:22:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:22:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:22:38 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:22:38 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:22:38 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(62): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:23:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:23:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:23:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:27:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:27:22 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:27:22 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:27:22 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(64): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:28:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:28:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:29:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:29:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:29:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:29:33 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('3')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '3')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:29:33 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('3')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '3')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:29:33 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('3')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '3')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:29:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:30:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:30:03 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:30:03 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:30:03 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:30:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:30:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:30:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:30:43 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:30:43 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:30:43 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:30:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-29 14:31:54 --> syntax error, unexpected token "break"
in APPPATH\Modules\Admin\Controllers\Users.php on line 69.
 1 SYSTEMPATH\Autoloader\Autoloader.php(285): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\wamp64\\www\\modelo\\app\\Modules\\Admin\\Controllers\\Users.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(263): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Modules\\Admin\\Controllers\\Users')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Modules\\Admin\\Controllers\\Users')
 4 SYSTEMPATH\CodeIgniter.php(873): class_exists('\\App\\Modules\\Admin\\Controllers\\Users', true)
 5 SYSTEMPATH\CodeIgniter.php(479): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:31:54 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(ParseError), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(ParseError), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ParseError))
#5 {main}
  thrown
【Previous Exception】
ParseError
syntax error, unexpected token "break"
#0 C:\wamp64\www\modelo\system\Autoloader\Autoloader.php(285): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\wamp64\\www\\m...')
#1 C:\wamp64\www\modelo\system\Autoloader\Autoloader.php(263): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Modules\\Adm...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Modules\\Adm...')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(873): class_exists('\\App\\Modules\\Ad...', true)
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(479): CodeIgniter\CodeIgniter->startController()
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:32:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:32:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:32:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 14:32:27 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('2')
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 14:32:27 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `adm_funcionarios`
WHERE `id` = :id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('2')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 14:32:27 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'id' in 'where clause'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(66): App\Modules\Admin\Models\UserModel->editRecord('2')
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('delete', '2')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 14:33:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:33:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:33:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:33:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:36:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:36:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:36:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:36:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:36:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:36:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:36:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:53:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:53:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:53:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:53:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 14:54:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:02:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:02:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
ERROR - 2023-09-29 16:02:31 --> mysqli_sql_exception: Unknown column 'depatamento' in 'field list' in C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\modelo\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `adm_fun...', 0)
#1 C:\wamp64\www\modelo\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `adm_fun...')
#2 C:\wamp64\www\modelo\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `adm_fun...')
#3 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `adm_fun...', Array, false)
#4 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(49): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#5 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(56): App\Modules\Admin\Models\UserModel->editRecord('3', Array)
#6 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('edit', '3')
#7 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#8 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-29 16:02:31 --> Unknown column 'depatamento' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `adm_funcionarios` SET `nome` = :nome:, `sobrenome` = :sobrenome:, `cpf` = :cpf:, `dt_contratacao` = :dt_contratacao:, `ativo` = :ativo:, `depatamento` = :depatamento:
WHERE `funcionario_id` = :funcionario_id:', [...], false)
 2 APPPATH\Modules\Admin\Models\UserModel.php(49): CodeIgniter\Database\BaseBuilder->update([...], [...])
 3 APPPATH\Modules\Admin\Controllers\Users.php(56): App\Modules\Admin\Models\UserModel->editRecord('3', [...])
 4 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('edit', '3')
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 16:02:31 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(mysqli_sql_exception), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(mysqli_sql_exception), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unknown column 'depatamento' in 'field list'
#0 C:\wamp64\www\modelo\system\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `adm_fun...', Array, false)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Models\UserModel.php(49): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#2 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Users.php(56): App\Modules\Admin\Models\UserModel->editRecord('3', Array)
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Users->users('edit', '3')
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Users))
#5 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-29 16:02:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:03:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:03:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:20:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:21:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:22:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:25:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:26:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:26:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:26:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:26:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:26:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:26:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:28:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:46:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 16:46:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 18:11:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 18:11:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 18:11:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 18:13:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 18:14:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-29 18:16:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
